format = """
[ ](bg:#82b1ff)\
$os\
$username\
$hostname\
[](fg:#82b1ff bg:#3b4261)\
$directory\
[](fg:#82b1ff bg:#3b4261)\
$git_branch\
$git_status\
[](fg:#3b4261 bg:#1d2230)\
$time\
[](fg:#1d2230)\
\n$character"""

[os]
disabled = false
style = "fg:#15161e bg:#82b1ff"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "fg:#15161e bg:#82b1ff bold"
style_root = "fg:#15161e bg:#82b1ff bold"
format = '[ $user ]($style)'

[hostname]
style = "fg:#15161e bg:#82b1ff bold"
ssh_only = false
format = "[ $hostname ]($style)"
trim_at = "-"
disabled = true

[directory]
style = "fg:#82b1ff bg:#3b4261"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[character]
vimcmd_symbol = '[V](bold green) '
success_symbol = '[](bold green)'
error_symbol = '[](bold red)'
